<a href="https://colab.research.google.com/github/madhavakirthickj2025cse-lab/FDS-Lab-Experiments/blob/main/exp_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

data = {
    "Country": [
        "UK", "Germany", "Japan", "UK", "France",
        "Japan", "Germany", "France", np.nan, "UK"
    ],

    "Age": [
        22, 35, 40, np.nan, 31, 27, 45, 38, 29, 33
    ],

    "Salary": [
        28000, 55000, 67000, 42000, 61000,
        np.nan, 72000, 49000, 53000, 58000
    ],

    "Purchased": [
        "No", "Yes", "No", "Yes", "Yes",
        "No", "Yes", "No", "Yes", "No"
    ]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

print("Dataset Information:")
df.info()

print("\nMode of Country:")
print(df["Country"].mode())

# Fill missing country using mode
df["Country"] = df["Country"].fillna(
    df["Country"].mode()[0]
)

# Fill missing age using median
df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

# Fill missing salary using rounded mean
df["Salary"] = df["Salary"].fillna(
    round(df["Salary"].mean())
)

print("\nAfter Data Preprocessing:")
display(df)

print("\nMissing Values After Preprocessing:")
print(df.isnull().sum())

Original Dataset:

   Country   Age   Salary Purchased
0       UK  22.0  28000.0        No
1  Germany  35.0  55000.0       Yes
2    Japan  40.0  67000.0        No
3       UK   NaN  42000.0       Yes
4   France  31.0  61000.0       Yes
5    Japan  27.0      NaN        No
6  Germany  45.0  72000.0       Yes
7   France  38.0  49000.0        No
8      NaN  29.0  53000.0       Yes
9       UK  33.0  58000.0        No

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    9 non-null      object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

Mode of Country:
0    UK
Name: Country, dtype: object

After Data Preprocessing:

   Country   Age   Salary Purchased
0       UK  22.0  28000.0        No
1  Germany  35.0  55000.0       Yes
2    Japan  40.0  67000.0        No
3       UK  33.0  42000.0       Yes
4   France  31.0  61000.0       Yes
5    Japan  27.0  53889.0        No
6  Germany  45.0  72000.0       Yes
7   France  38.0  49000.0        No
8       UK  29.0  53000.0       Yes
9       UK  33.0  58000.0        No

Missing Values After Preprocessing:
Country      0
Age          0
Salary       0
Purchased    0
dtype: int64